### ISSUE TITLE
op运行求助

### ISSUE THREAD

**Issue by r1172464137** [imguoliwei/UA2F-cpp#1]
bin文件夹中的可执行文件在openwrt上运行需要依赖nftables吗

**Comment by imguoliwei** [comment]
不需要，代码没有假设你使用iptables还是nftables

**Comment by r1172464137** [comment]
> 不需要，代码没有假设你使用iptables还是nftables

好嘞，大佬能举个iptables的规则例子吗

**Comment by imguoliwei** [comment]
iptables -t mangle -N ua2f
iptables -t mangle -A ua2f -m connmark --mark 43 -j RETURN
iptables -t mangle -A ua2f -p tcp -m multiport --dports 22,443 -j RETURN
iptables -t mangle -A ua2f -j NFQUEUE --queue-balance 10010:10013
iptables -t mangle -A POSTROUTING -o pppoe-wan -p tcp -j ua2f

ip6tables -t mangle -N ua2f
ip6tables -t mangle -A ua2f -m connmark --mark 43 -j RETURN
ip6tables -t mangle -A ua2f -p tcp -m multiport --dports 22,443 -j RETURN
ip6tables -t mangle -A ua2f -j NFQUEUE --queue-balance 10010:10013
ip6tables -t mangle -A POSTROUTING -o pppoe-wan -p tcp -j ua2f
大概是这样

**Comment by r1172464137** [comment]
> iptables -t mangle -N ua2f iptables -t mangle -A ua2f -m connmark --mark 43 -j RETURN iptables -t mangle -A ua2f -p tcp -m multiport --dports 22,443 -j RETURN iptables -t mangle -A ua2f -j NFQUEUE --queue-balance 10010:10013 iptables -t mangle -A POSTROUTING -o pppoe-wan -p tcp -j ua2f
> 
> ip6tables -t mangle -N ua2f ip6tables -t mangle -A ua2f -m connmark --mark 43 -j RETURN ip6tables -t mangle -A ua2f -p tcp -m multiport --dports 22,443 -j RETURN ip6tables -t mangle -A ua2f -j NFQUEUE --queue-balance 10010:10013 ip6tables -t mangle -A POSTROUTING -o pppoe-wan -p tcp -j ua2f 大概是这样

谢谢大佬

**Comment by r1172464137** [comment]
编译的时候报了错
`error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’?
  102 |     auto const nlh = nfq_nlmsg_put(buf, NFQNL_MSG_VERDICT, queue_num);
      |                      ^~~~~~~~~~~~~
      |                      nfq_nlmsg_parse
`

`
345:16: error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’?
  345 |     auto nlh = nfq_nlmsg_put(buf.get(), NFQNL_MSG_CONFIG, queue_number);
      |                ^~~~~~~~~~~~~
      |                nfq_nlmsg_parse
`

**Comment by imguoliwei** [comment]
我是这样编译的，我这个方法可能不是最快。先编译Zxilly的UA2F，按[ci.yml](https://github.com/Zxilly/UA2F/blob/master/.github/workflows/ci.yml)里面的命令，这样会下载好需要的依赖。然后删除package/UA2F/里面的所有文件，把ua2f-mix.cpp复制到里面，然后再用openwrt sdk的g++直接编译。我刚才更新了README，你参考下。

**Comment by imguoliwei** [comment]
我发现你的[ci.yml](https://github.com/r1172464137/UA2F/blob/master/.github/workflows/ci.yml)有一些多余的`cd package/UA2F`和其他错误，我建议你在本地编译，这样容易发现错误的命令，也容易观察目录结构。我自己也是本地编译的。

**Comment by imguoliwei** [comment]
> 编译的时候报了错 `error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 102 | auto const nlh = nfq_nlmsg_put(buf, NFQNL_MSG_VERDICT, queue_num); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse `
> 
> `345:16: error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 345 | auto nlh = nfq_nlmsg_put(buf.get(), NFQNL_MSG_CONFIG, queue_number); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse`

这个问题已经查清楚了，某些系统，比如Ubuntu 20.04 LTS的libnetfilter-queue-dev版本太低，没有那些函数。我已经云编译了一些常见路由器CPU架构的二进制程序，你可以在[ci.yml](https://github.com/imguoliwei/UA2F-cpp/blob/main/.github/workflows/ci.yml)查看具体的编译命令

**Comment by Digital-z** [comment]
> 编译的时候报了错 `error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 102 | auto const nlh = nfq_nlmsg_put(buf, NFQNL_MSG_VERDICT, queue_num); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse `
> 
> `345:16: error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 345 | auto nlh = nfq_nlmsg_put(buf.get(), NFQNL_MSG_CONFIG, queue_number); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse`

请问你是怎么编译这个大佬的项目的，是使用的云编译么

**Comment by r1172464137** [comment]
> > 编译的时候报了错 `error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 102 | auto const nlh = nfq_nlmsg_put(buf, NFQNL_MSG_VERDICT, queue_num); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse `
> > `345:16: error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 345 | auto nlh = nfq_nlmsg_put(buf.get(), NFQNL_MSG_CONFIG, queue_number); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse`
> 
> 请问你是怎么编译这个大佬的项目的，是使用的云编译么

作者发布了bin文件

**Comment by Digital-z** [comment]
> > > 编译的时候报了错 `error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 102 | auto const nlh = nfq_nlmsg_put(buf, NFQNL_MSG_VERDICT, queue_num); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse `
> > > `345:16: error: ‘nfq_nlmsg_put’ was not declared in this scope; did you mean ‘nfq_nlmsg_parse’? 345 | auto nlh = nfq_nlmsg_put(buf.get(), NFQNL_MSG_CONFIG, queue_number); | ^~~~~~~~~~~~~ | nfq_nlmsg_parse`
> > 
> > 
> > 请问你是怎么编译这个大佬的项目的，是使用的云编译么
> 
> 作者发布了bin文件

作者realease里面的文件下载下来就29k，那个该怎么使用呢，我对这个不是很明白，希望能求个联系方式问一些问题，我会给予相应报酬
