### ISSUE TITLE
如何与 MWAN3 共存

### ISSUE THREAD

**Issue by 0xffffharry** [imguoliwei/UA2F-cpp#2]
加入 --disable-ct-mark 参数就行吗

**Comment by imguoliwei** [comment]
防火墙也要改。删除`iptables -t mangle -A ua2f -m connmark --mark 43 -j RETURN`
这样做会导致没有UA的TCP包也进入netfilter queue。如果你觉得CPU占用太高，可以考虑只处理80端口。

**Comment by 0xffffharry** [comment]
感谢，我这边似乎只会检测80端口上的http，所以没什么影响
