### ISSUE TITLE
我有个想法，不知行不行

### ISSUE THREAD

**Issue by Kudryavka03** [imguoliwei/UA2F-cpp#3]
tcp timestamp能不能根据路由器的时间去生成而不是抹掉？

**Comment by imguoliwei** [comment]
理论上可以，但是我觉得没必要这样做
首先，我在readme中写的iptables规则只是参考配置，与上面的nftables 配置相比，少了一条
`tcp flags syn tcp option timestamp exists counter queue num 10010-10013 fanout`
如果你使用iptables，想清除TCP Timestamps，需要加上
`iptables -t mangle -I ua2f -p tcp --syn -j NFQUEUE --queue-balance 10010:10013`

如果你想生成TCP Timestamps，分2种情况：
1.路由器发出的TCP包已经存在Timestamps。这种情况下理论上可以根据路由器的时间去生成Timestamps。但是Timestamps本身并不是必需的，直接清除也合情合理。你说你在csdn找到的内核模块是[NAT网关自动去掉TCP syn包的时间戳](https://blog.csdn.net/gdfhhj/article/details/87450737)吗？他的代码也是直接清除的。
2.路由器发出的TCP包不存在Timestamps。这种情况下因为TCP包的长度发生了变化，连接需要重新同步，整个项目要[重写](https://github.com/Zxilly/UA2F/issues/9#issuecomment-825393107)，目前不考虑这种情况。

**Comment by imguoliwei** [comment]
修改Timestamps在实际运行中很可能会导致网络异常。因为当发送端发送了TSval后，如果接收端回复中也有Timestamps选项，那么接收端的TSecr应该与发送端的TSval相同。一旦修改了发送端的TSval，必然导致接下来收到的TSecr对不上。

**Comment by Kudryavka03** [comment]
感谢解答。另外我还有个想法，就是能不能根据情况直接吧整个useragent字段去掉。比如ua字段含有MicroMessage Client的就保留ua，ua没有该字段就去掉（本人想自己修改但无奈c++真不会写）

**Comment by Kudryavka03** [comment]
直接吧整个User-Agent去掉这种。毕竟很少用http传输关键数据了，一般来说也就资源服务器这些，而且这些服务器通常也不会检测ua的

**Comment by imguoliwei** [comment]
这样做很危险，由于不方便修改TCP包的长度，所以只能用某些字符(如空格)替换User-Agent。有些服务器不能识别这种HTTP报文，尤其是当User-Agent是第一个首部字段时。

我的实验结果如下：
1.原报文
```bash
echo -e "GET / HTTP/1.1\r\nUser-agent: Mozilla/4.0\r\nHost: www.baidu.com\r\nAccept: */*\r\n\r\n"|nc -v 14.215.177.39 80
```
结果 `HTTP/1.1 200 OK`
```bash
echo -e "GET / HTTP/1.1\r\nUser-agent: Mozilla/4.0\r\nHost: weibo.com\r\nAccept: */*\r\n\r\n"|nc -v 180.149.138.246 80
```
结果 `HTTP/1.1 301 Moved Permanently`

2.删除前面的换行符
```bash
echo -e "GET / HTTP/1.1                           \r\nHost: www.baidu.com\r\nAccept: */*\r\n\r\n"|nc -v 14.215.177.39 80
```
结果 `HTTP/1.1 400 Bad Request`
```bash
echo -e "GET / HTTP/1.1                           \r\nHost: weibo.com\r\nAccept: */*\r\n\r\n"|nc -v 180.149.138.246 80
```
结果 `HTTP/1.1 301 Moved Permanently`

3.删除后面的换行符
```bash
echo -e "GET / HTTP/1.1\r\n                           Host: www.baidu.com\r\nAccept: */*\r\n\r\n"|nc -v 14.215.177.39 80
```
结果 `HTTP/1.1 200 OK`
```bash
echo -e "GET / HTTP/1.1\r\n                           Host: weibo.com\r\nAccept: */*\r\n\r\n"|nc -v 180.149.138.246 80
```
结果 `HTTP/1.1 400 Bad Request`

由此可见，去掉整个User-Agent将导致HTTP报文不符合标准，有可能直接返回400，我不建议这样做
如果你只是想自定义User-Agent，可以直接修改代码
https://github.com/imguoliwei/UA2F-cpp/blob/a3f4ce858021b2702fbe4940a48f05a58cb1f47a/src/ua2f-mix.cpp#L23-L24

**Comment by Kudryavka03** [comment]
那如果我将user-agent这个头替换成其他文字比如agent-user呢（
主要是我们学校还能检测到我们使用多终端共享，开始怀疑是不是某些ua长度不够，比如微信这些，导致网关识别到了多个ua
（然后这去掉useragent点子也是我借我同学的校园网路由器抓包发现的）

**Comment by imguoliwei** [comment]
你可以试试，只需要稍微改动一些代码
把UA_STR改成
```C++
constexpr char UA_STR[] = "Agent-User: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"; 
```
然后把
https://github.com/imguoliwei/UA2F-cpp/blob/a3f4ce858021b2702fbe4940a48f05a58cb1f47a/src/ua2f-mix.cpp#L270-L271
改成
```C++
            nfq_tcp_mangle_ipv4(pktb, uaOffset - 12, uaLength + 12, ua_result.data(), uaLength + 12) :
            nfq_tcp_mangle_ipv6(pktb, uaOffset - 12, uaLength + 12, ua_result.data(), uaLength + 12)
```

**Comment by Kudryavka03** [comment]
删除UA字样后依然被检测到共享......
（虽然已经不是程序上的问题了）
但是也抓了包，推测有以下可能
1.手机的generate_204，不同的手机会访问自家的204服务器去确认联网状态
2.微信的mmtls，抓包观察发现微信的mmtls短链接，HTTP GET mmtls/xxxxxx
后面的xxxxxx是微信随机生成的，转换成十进制数字实际下来是递增的，可能学校服务器会抓住这里取检测，并且xxxx可能也和微信数据有关
3.微信的DNS地址取得是明文的，会在网址后面加上用户特征
4.TCP Window和TCP Window Scale
1和3我可以加nginx解决，但是微信的mmtls我还暂时不清楚他是怎么工作的
所以，现在我想问下，如果我想改TCP Window和Window Scale的话，我该怎么办（

**Comment by imguoliwei** [comment]
这个你要自己写代码了。改Window Scale的代码跟clearTcpTimestamps函数差不多，改TCP Window也不难。但是改太多东西有可能导致网络不稳定。
想自己写的话，可以看[libnetfilter_queue](https://www.netfilter.org/projects/libnetfilter_queue/doxygen/html/)和[libmnl](https://imguoliwei.github.io/docs/libmnl/index.html)的文档
