### ISSUE TITLE
关于ipid的疑惑

### ISSUE THREAD

**Issue by zfdx123** [imguoliwei/UA2F-cpp#4]
尊敬的开发者，请问该软件的ipid选项是否可以代替rkp-ipid

**Comment by zfdx123** [comment]
我注意到nftables配置中'''meta mark set mark or 0x10'''与rkp-ipid的nftables配置似乎相同，不知道会不会存在冲突或解决办法？

**Comment by imguoliwei** [comment]
基于性能考虑，建议使用rkp-ipid来修改ipid。`meta mark set mark or 0x10`就是rkp-ipid的配置，如果用本项目来修改ipid则不需要`meta mark set mark or 0x10`

**Comment by zfdx123** [comment]
哦好的，谢谢您

**Comment by zfdx123** [comment]
```
ip ttl set 64
ip6 hoplimit set 64
```

这两句也就是说将TTL设置为64和

```
counter packets 0 bytes 0
```

应该是一样的效果对吧
